import type { Metadata } from "next";
import { Livvic } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const livvic = Livvic({
  variable: "--font-livvic",
  weight: ['400', '600', '700'],
  style: ['italic', 'normal'],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "myteam website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${livvic.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
